import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Providers } from "@/services/Store/provider";
import AntdThemeProvider from "@/components/AntdThemeProvider";
import { cookies } from "next/headers";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AntdRegistry>
            <AntdThemeProvider>{children}</AntdThemeProvider>
          </AntdRegistry>
        </Providers>
      </body>
    </html>
  );
}
